#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, fileinput, re

if __name__ == "__main__":
	useless_texts = [
		"-----original message-----",
		"mailto:it-support-schaeffler-group@schaeffler.com",
		"# == == == == == == == ==",
		"308 springhill farm rd.",
		"308 springhill farm road",
		"3401 old airport rd.",
		"3401 old airport road",
		"an: it-support schaeffler-group",
		"best regards technische it - schaeffler group ",
		"best regards",
		"can you please have him call us at ext 1188.",
		"category: userselfservice",
		"closing this ticket.",
		"closing this tkt.",
		"copying, distribution, or use of the contents of this information is prohibited.",
		"dear madam or sir,",
		"dear sir,",
		"director: north america technology services",
		"disclaimer this electronic message transmission contains information that may be confidential or privileged.",
		"do you know if this has been taken care of?",
		"e-mail: it-support-sg-na@schaeffler.com",
		"email - it-support-sg-na@schaeffler.com",
		"email –  phone – ",
		"email –  phone",
		"email – self service – ",
		"email – self service",
		"email ? it-support-sg-na@schaeffler.com",
		"email address: tom.miller@schaeffler.com",
		"email: it-support-sg-na@schaeffler.com",
		"fort mill, sc 29715",
		"from: it-support-schaeffler-group@schaeffler.com",
		"good morning,",
		"gracias por usar el schaeffler group it service desk.",
		"gracias,",
		"hello, ",
		"hola, hemos tratado de comunicarnos con usted.",
		"http://tsd.de.ina.com/magicsshd",
		"http://www.schaeffler.us",
		"i called user, no answer.",
		"i left a vm.",
		"if you are not the intended recipient, be aware that any disclosure,",
		"if you have received this electronic transmission in error,",
		"if you require further assistance, please contact the schaeffler group it service desk.",
		"if you still need assitance, please call at ext 1188.",
		"importance: high",
		"it operations schaeffler group",
		"it support schaeffler group north america",
		"it support schaeffler group",
		"it support",
		"it-service-desk schaeffler group e-mail: it-support-sg@schaeffler.com",
		"it-service-desk schaeffler group",
		"it-support schaeffler-group north america",
		"it-support-sg-na@schaeffler.com",
		"it-support, ina india",
		"it-support,",
		"it-support",
		"it/client coordinator",
		"luk usa llc",
		"mailing user.",
		"mit freundlichen gruessen",
		"mit freundlichen grüßen / best regards / saludos",
		"mit freundlichen grüßen",
		"na-editeam@schaeffler.com;",
		"not able to reach user.",
		"on behalf of it-support schaeffler-group",
		"original message from: it-support-schaeffler-group@schaeffler.com",
		"para ayuda técnico por favor comunicase con el schaeffler group it service desk:",
		"para: it-support schaeffler-group north america",
		"phone - (888) 462-6811 or x1188",
		"phone – extension 1188 or toll free (888) 462-6811",
		"phone ? (888) 462-6811",
		"phone ext: x1188 or 1-888-462-6811",
		"phone: extension 1188 or toll free (888) 462-6811",
		"please call me back.",
		"please close ticket.",
		"please ignore this ticket.",
		"please notify the sender and delete the material from any computer.",
		"please rush!!",
		"por teléfono: x1188 o 001-888-462-6811",
		"problem resolved.",
		"regards,",
		"regards.",
		"regards",
		"saludos, - schaeffler service desk, norteamérica",
		"schaeffler group north america email - it-support-sg-na@schaeffler.com",
		"schaeffler group usa inc.",
		"schaeffler group usa",
		"schaeffler it service desk, north america",
		"schaeffler it service desk",
		"schaeffler north america",
		"schaeffler service desk, norteamérica",
		"schaeffler service desk, north america",
		"schaeffler service desk",
		"self service - http://tsd.de.ina.com/magicsshd",
		"self service - http://tsduss.de.ina.com/magicsshd",
		"self service ? http://tsd.de.ina.com/magicsshd",
		"self service: http://tsd.de.ina.com/magicsshd",
		"sent email to get an update on ticket.",
		"sent email to get an update.",
		"sent email to get update on ticket.",
		"sent email to get update.",
		"si sigue teniedo problemas, por favor llamenos.",
		"sorry for the delay again",
		"sorry for the delay",
		"sorry for the late answer,",
		"sorry for the late answer",
		"sorry, ",
		"su petición a sido completado.",
		"telephone: 01805 22 33 11",
		"thank you for contacting the north america service desk. regards,",
		"thank you for contacting the north america service desk.",
		"thank you for using the schaeffler group it service desk.",
		"thank you, -",
		"thank you, it support schaeffler group",
		"thank you, it support",
		"thank you, rodrigo melendez",
		"thank you, schaeffler it service desk, na",
		"thank you, schaeffler it service desk,",
		"thank you,",
		"thank you!",
		"thank you.",
		"thank you ",
		"thank you",
		"thanks, it support schaeffler group",
		"thanks, it support",
		"thanks,",
		"thanks!",
		"thanks. regards,",
		"thanks.",
		"the information is intended to be for the use of the individual or entity named above.",
		"to: it-support schaeffler-group north america",
		"to: it-support schaeffler-group",
		"troubleshooting data: ",
		"urgent request!",
		"urgent request.",
		"urgent!!! please rush!!",
		"urgent!!",
		"we have tried to contact you regarding your issue/request.",
		"we will now close this ticket.",
		"with best regards,",
		"wooster, ohio 44691",
		"wooster, oh 44691",
		"wooster,oh 44691",
		"www.luk.com",
		"x1188 o 001-888-462-6811",
		"x1188 or 1-888-462-6811",
		"your request has been completed.",
		"your ticket request."
	]
	useless_texts = sorted(useless_texts, key=len, reverse=True)
	for text in useless_texts:
		print '"', text, '",'
